//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INEC.TEMA1.ACCESO_DATOS
{
    using System;
    using System.Data.Entity;
    using INEC.TEMA1.COMUN;
    using System.Data.Entity.Infrastructure;
    
    public partial class INECBDEntities : DbContext
    {
        public INECBDEntities()
            : base("name=INECBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
