//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INEC.TEMA1.COMUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public int ID_DIRECCION { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string DESCRIPCION_DIRECCION { get; set; }
        public byte[] FOTO_DIRECCION { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
