//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INEC.TEMA1.COMUN
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.DIRECCIONs = new HashSet<DIRECCION>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO1_USUARIO { get; set; }
        public string APELLIDO2_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_USUARIO { get; set; }
        public string CODIGO_USUARIO { get; set; }
        public byte[] FOTO_USUARIO { get; set; }
        public string CREACION_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_USUARIO { get; set; }
        public string MODIFICACION_USUARIO { get; set; }
        public Nullable<System.DateTime> MODIFICACION_FECHA_USUARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCION> DIRECCIONs { get; set; }
    }
}
