CREATE TABLE [INEC.SEC].[DIRECCION] (
    [ID_DIRECCION]          INT             IDENTITY (1, 1) NOT NULL,
    [ID_USUARIO]            INT             NULL,
    [DESCRIPCION_DIRECCION] VARCHAR (400)   NULL,
    [FOTO_DIRECCION]        VARBINARY (MAX) NULL,
    CONSTRAINT [PK_DIRECCION] PRIMARY KEY CLUSTERED ([ID_DIRECCION] ASC),
    CONSTRAINT [FK_DIRECCION_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [INEC.SEC].[USUARIO] ([ID_USUARIO])
);

