CREATE TYPE [INEC.SEC].[USUARIO_TIPO] AS TABLE (
    [ID_USUARIO]                 INT             NOT NULL,
    [NOMBRE_USUARIO]             VARCHAR (100)   NULL,
    [APELLIDO1_USUARIO]          VARCHAR (100)   NULL,
    [APELLIDO2_USUARIO]          VARCHAR (100)   NULL,
    [FECHA_NACIMIENTO_USUARIO]   DATE            NULL,
    [CODIGO_USUARIO]             VARCHAR (10)    NULL,
    [FOTO_USUARIO]               VARBINARY (MAX) NULL,
    [CREACION_USUARIO]           VARCHAR (10)    NULL,
    [FECHA_CREACION_USUARIO]     DATETIME        NULL,
    [MODIFICACION_USUARIO]       VARCHAR (10)    NULL,
    [MODIFICACION_FECHA_USUARIO] DATETIME        NULL);

