CREATE TABLE [dbo].[cliente_PersonaPreferencias] (
    [COD_PERSONA]     INT NOT NULL,
    [COD_PREFERENCIA] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([COD_PERSONA] ASC, [COD_PREFERENCIA] ASC),
    CONSTRAINT [FK365F29383A9E1404] FOREIGN KEY ([COD_PERSONA]) REFERENCES [dbo].[cliente_Persona] ([id]),
    CONSTRAINT [FK365F2938E2A0581C] FOREIGN KEY ([COD_PREFERENCIA]) REFERENCES [dbo].[cliente_Preferencias] ([IDE_CODIGO])
);

