CREATE TABLE [dbo].[cliente_Sucursal] (
    [id]                          INT           IDENTITY (1, 1) NOT NULL,
    [nombre]                      VARCHAR (120) NULL,
    [COD_IDENTIFICACION_SUCURSAL] VARCHAR (3)   NULL,
    [desde1]                      INT           NOT NULL,
    [hasta1]                      INT           NOT NULL,
    [desde2]                      INT           NULL,
    [hasta2]                      INT           NULL,
    [desde3]                      INT           NULL,
    [hasta3]                      INT           NULL,
    [horario]                     VARCHAR (180) NULL,
    [foto]                        IMAGE         NULL,
    [mapa]                        IMAGE         NULL,
    [direccion_id]                NUMERIC (19)  NULL,
    [empresa_id]                  INT           NULL,
    [FEC_APERTURA]                DATETIME      NULL,
    [DSC_EMAIL_SOPORTE]           VARCHAR (90)  DEFAULT ('') NOT NULL,
    [mostrar_en_web]              TINYINT       CONSTRAINT [DF_cliente_Sucursal_mostrar_en_web] DEFAULT ((0)) NOT NULL,
    [zona_id]                     INT           DEFAULT ((1)) NOT NULL,
    [es_sucursal]                 BIT           NULL,
    [SUC_ACTIVA]                  BIT           NULL,
    [CodigoPais]                  INT           NULL,
    [DireccionesIP]               VARCHAR (180) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK98C877456921FD8D] FOREIGN KEY ([empresa_id]) REFERENCES [dbo].[cliente_Empresa] ([id]),
    CONSTRAINT [FK98C8774597593927] FOREIGN KEY ([zona_id]) REFERENCES [dbo].[cliente_Zona] ([id]),
    CONSTRAINT [FK98C87745BE83176D] FOREIGN KEY ([direccion_id]) REFERENCES [dbo].[cliente_Direccion] ([id])
);

