CREATE TABLE [dbo].[cliente_Direccion] (
    [id]                   NUMERIC (19)   IDENTITY (1, 1) NOT NULL,
    [descripcion]          VARCHAR (1024) NULL,
    [telefono1]            VARCHAR (45)   NULL,
    [telefono2]            VARCHAR (45)   NULL,
    [telefono3]            VARCHAR (45)   NULL,
    [telefono4]            VARCHAR (45)   NULL,
    [tipoTelefono1]        INT            NULL,
    [tipoTelefono2]        INT            NULL,
    [tipoTelefono3]        INT            NULL,
    [tipoTelefono4]        INT            NULL,
    [celular]              VARCHAR (255)  NULL,
    [email1]               VARCHAR (90)   NULL,
    [email2]               VARCHAR (90)   NULL,
    [division_id]          INT            NULL,
    [subdivision_id]       INT            NULL,
    [pais_id]              INT            NULL,
    [ConSubdivision]       INT            NULL,
    [ImagenEntrega]        VARCHAR (16)   NULL,
    [HorarioEntrega]       VARCHAR (120)  NULL,
    [Localizador]          VARCHAR (255)  NULL,
    [Nombre]               VARCHAR (40)   NULL,
    [latitud]              VARCHAR (12)   NULL,
    [longitud]             VARCHAR (12)   NULL,
    [CoordenadaGeografica] VARCHAR (120)  NULL,
    [ConRuta]              INT            NULL,
    [ConDistrito]          INT            NULL,
    [CodigoPais]           INT            NULL,
    [autorizado]           VARCHAR (40)   NULL,
    CONSTRAINT [PK__cliente_Direccio__46DD686B] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_m7npi3okfo2qvvsut95jyrn5] FOREIGN KEY ([ConSubdivision]) REFERENCES [dbo].[cliente_Subdivision] ([ConSubdivision]),
    CONSTRAINT [FK_n3a2g7hemftjb797ia5kxa1t9] FOREIGN KEY ([ConRuta]) REFERENCES [dbo].[correo_RutaEntrega] ([ConRuta])
);

