CREATE TABLE [dbo].[correo_Ejecutivo] (
    [NUM_EJECUTIVO] INT NOT NULL,
    [CodigoPais]    INT NULL,
    [COD_PERSONA]   INT NOT NULL,
    [COD_EMPRESA]   INT NULL,
    CONSTRAINT [PK__correo_Ejecutivo__7FE0DB9D] PRIMARY KEY CLUSTERED ([NUM_EJECUTIVO] ASC),
    CONSTRAINT [FKC443FFF73A9E1404] FOREIGN KEY ([COD_PERSONA]) REFERENCES [dbo].[cliente_Persona] ([id]),
    CONSTRAINT [FKC443FFF7C9E8F5BE] FOREIGN KEY ([COD_EMPRESA]) REFERENCES [dbo].[cliente_Empresa] ([id])
);

