CREATE TABLE [dbo].[correo_ContratoAlianza] (
    [COD_TIPO_CONTRATO] INT NOT NULL,
    [COD_ALIANZA]       INT NOT NULL,
    PRIMARY KEY CLUSTERED ([COD_TIPO_CONTRATO] ASC, [COD_ALIANZA] ASC),
    CONSTRAINT [FK24BA6EED328C43A3] FOREIGN KEY ([COD_TIPO_CONTRATO]) REFERENCES [dbo].[correo_Contrato] ([IDE_CODIGO])
);

