CREATE TABLE [dbo].[JETBOX_INTEGRA_CLIENTES] (
    [CLN_CODIGO]                 INT           NOT NULL,
    [CLN_NOMBRE]                 VARCHAR (50)  NULL,
    [CLN_NOMBREL]                VARCHAR (100) NULL,
    [CLN_TIPOID]                 VARCHAR (1)   NULL,
    [CLN_IDENTIFICADOR]          VARCHAR (20)  NULL,
    [CLN_DIRECCION]              VARCHAR (255) NULL,
    [CLN_TELEFONO1]              VARCHAR (20)  NULL,
    [CLN_TELEFONO2]              VARCHAR (20)  NULL,
    [CLN_FAX1]                   VARCHAR (20)  NULL,
    [CLN_FAX2]                   VARCHAR (20)  NULL,
    [CLN_EMAIL1]                 VARCHAR (80)  NULL,
    [CLN_EMAIL2]                 VARCHAR (80)  NULL,
    [CLN_TIPO]                   VARCHAR (1)   NULL,
    [CLN_CUENTA]                 VARCHAR (25)  NULL,
    [CLN_CUENTA2]                VARCHAR (25)  NULL,
    [CLN_VENDEDOR]               INT           NULL,
    [CLN_CONTACTO]               VARCHAR (40)  NULL,
    [CLN_FECHADIG]               DATETIME      NULL,
    [CLN_FUNCIONARIODIG]         VARCHAR (15)  NULL,
    [CLN_IMPVENTAS]              VARCHAR (1)   NULL,
    [CLN_Observaciones]          TEXT          NULL,
    [CLN_Instrucciones]          TEXT          NULL,
    [CLN_Referidopor]            VARCHAR (40)  NULL,
    [CLN_Compania]               VARCHAR (20)  NULL,
    [CLN_CodigoAlfa]             VARCHAR (50)  NOT NULL,
    [CLN_PlazoPago]              INT           NULL,
    [CLN_Categoria]              VARCHAR (1)   NULL,
    [CLN_ERR_Nombre]             VARCHAR (100) NULL,
    [CLN_ERR_Apellido1]          VARCHAR (100) NULL,
    [CLN_ERR_Apellido2]          VARCHAR (100) NULL,
    [CLN_ERR_Casillero]          VARCHAR (100) NULL,
    [CLN_ERR_NombreCorporativo]  VARCHAR (200) NULL,
    [CLN_ERR_Pais]               INT           NULL,
    [CLN_ERR_Provincia]          INT           NULL,
    [CLN_ERR_Canton]             INT           NULL,
    [CLN_ERR_Distrito]           INT           NULL,
    [CLN_ERR_Direccion1]         VARCHAR (200) NULL,
    [CLN_ERR_Direccion2]         VARCHAR (200) NULL,
    [CLN_ERR_Direccion3]         VARCHAR (200) NULL,
    [CLN_ERR_Apartado]           VARCHAR (100) NULL,
    [CLN_ERR_ZipCode]            VARCHAR (100) NULL,
    [CLN_ERR_CiudadAptdo]        VARCHAR (100) NULL,
    [CLN_ERR_Correo1]            VARCHAR (200) NULL,
    [CLN_ERR_Correo2]            VARCHAR (200) NULL,
    [CLN_ERR_TelCasa]            VARCHAR (100) NULL,
    [CLN_ERR_TelMovil]           VARCHAR (100) NULL,
    [CLN_ERR_LugarTrabajo]       VARCHAR (200) NULL,
    [CLN_ERR_TelTrabajo]         VARCHAR (100) NULL,
    [CLN_ERR_Fax]                VARCHAR (100) NULL,
    [CLN_ERR_TipoCuenta]         VARCHAR (1)   NULL,
    [CLN_ERR_FechaAfiliacion]    DATETIME      NULL,
    [CLN_ERR_Estado]             VARCHAR (1)   NULL,
    [CLN_ERR_EmisorTarjeta]      VARCHAR (3)   NULL,
    [CLN_ERR_TipoTarjeta]        VARCHAR (1)   NULL,
    [CLN_ERR_NumeroTarjeta]      VARCHAR (50)  NULL,
    [CLN_ERR_FechaVenceTarjeta]  DATETIME      NULL,
    [CLN_ERR_CRMFechaNacimiento] DATETIME      NULL,
    [CLN_ERR_CRMGenero]          VARCHAR (1)   NULL,
    [CLN_ERR_CRMEstadoCivil]     VARCHAR (1)   NULL,
    [CLN_ERR_CRMNombreConyugue]  VARCHAR (200) NULL,
    [CLN_ERR_FechaExporta]       DATETIME      NULL
);

